[programs.devnet]
gifportal = "9YN2AnKro5ihCfWX6ShbWiopvrUhywUwqDNykzB3Zhn1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kallu/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/gifportal.js"
